/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.user;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

import org.apache.poi.ss.formula.functions.T;

/**
 *
 * @author divya
 */
public class attendance extends javax.swing.JInternalFrame {

    /**
     * Creates new form attendance
     */
    public attendance() {
        initComponents();
        
        comsub.setSelectedItem(null);
        
         this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
    ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        comsem = new javax.swing.JComboBox<>();
        comdept = new javax.swing.JComboBox<>();
        btnsearch = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        txtdate = new com.toedter.calendar.JDateChooser();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtrollno = new javax.swing.JTextField();
        comsem1 = new javax.swing.JComboBox<>();
        comdept1 = new javax.swing.JComboBox<>();
        comstatus = new javax.swing.JComboBox<>();
        btnsubmit = new javax.swing.JButton();
        comsub = new javax.swing.JComboBox<>();
        ssubject = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblattendance = new javax.swing.JTable();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("jCheckBoxMenuItem3");

        setBorder(null);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("department:");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setText("semester:");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setText("subject:");

        comsem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "I", "II", "III", "IV", "V", "VI" }));

        comdept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "BCA", "CS" }));
        comdept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comdeptActionPerformed(evt);
            }
        });

        btnsearch.setBackground(new java.awt.Color(255, 102, 0));
        btnsearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsearch.setForeground(new java.awt.Color(255, 255, 255));
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setText("Date :");

        txtdate.setDateFormatString("yyyy-MM-dd");
        txtdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setText("name :");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel30.setText("roll no :");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel31.setText("semester:");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel32.setText("department:");

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel33.setText("status :");

        txtname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        txtrollno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtrollno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrollnoActionPerformed(evt);
            }
        });

        comsem1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "I", "II", "III", "IV", "V", "VI" }));

        comdept1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "BCA", "CS" }));

        comstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "present", "absent", " " }));

        btnsubmit.setBackground(new java.awt.Color(255, 102, 0));
        btnsubmit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnsubmit.setText("Submit");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });

        ssubject.setText("search subject");
        ssubject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ssubjectMouseClicked(evt);
            }
        });
        ssubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssubjectActionPerformed(evt);
            }
        });

        tblattendance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "name ", "roll no", "semester", "department"
            }
        ) {
            Class<T>[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class<T> getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblattendance.setColumnSelectionAllowed(true);
        tblattendance.getTableHeader().setReorderingAllowed(false);
        tblattendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblattendanceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblattendance);
        tblattendance.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblattendance.getAccessibleContext().setAccessibleParent(jScrollPane2);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(jLabel26)
                            .addComponent(jLabel25)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel29)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel28)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comsem1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comdept1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtrollno, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsubmit)
                            .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsearch))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel31)))
                        .addGap(216, 216, 216))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comdept, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comsem, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comsub, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(ssubject)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(comsem, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(comdept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(ssubject)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comsub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnsearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(txtrollno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(comsem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comdept1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(comstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnsubmit)
                        .addGap(0, 77, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
    if(comsem.getSelectedItem().equals("select")){
        JOptionPane.showMessageDialog(this,"please select your semester");
        comsem.setSelectedItem("select");
        comsem.grabFocus(); 
    } else if(comdept.getSelectedItem().equals("select")){
        JOptionPane.showMessageDialog(this,"please select your department");
        comdept.setSelectedItem("select");
        comdept.grabFocus();
    } else if(comsub.getSelectedItem().equals("select")){
        JOptionPane.showMessageDialog(this,"please select your subject");
        comsub.setSelectedItem("select");
        comsub.grabFocus();
    }else { 
        try {
            String semester=(String) comsem.getSelectedItem();
            String department=(String) comdept.getSelectedItem(); 
            String subject=(String) comsub.getSelectedItem();
            Class.forName("com.mysql.jdbc.Driver");
            Connection 
            con=DriverManager.getConnection("jdbc:mysql://localhost/attendance_ms","root","");

            PreparedStatement ps=con.prepareStatement("select * from student_tb where semester='"+semester+"' and department='"+department+"' and subject1='"+subject+"' or subject2='"+subject+"' or subject3='"+subject+"' or subject4='"+subject+"' or subject5='"+subject+"' ");
            ResultSet rs=ps.executeQuery();

            ResultSetMetaData rsd=rs.getMetaData();
            int c=rsd.getColumnCount(); 
            DefaultTableModel dft=(DefaultTableModel)tblattendance.getModel();
            dft.setRowCount(0);

            while (rs.next()){
                Vector<String> v2=new Vector<String>();
                for(int i=1;i<=c;i++){
                    v2.add(rs.getString("name"));
                    v2.add(rs.getString("rollno"));
                    v2.add(rs.getString("semester"));
                    v2.add(rs.getString("department"));
                }
            dft.addRow(v2); 
            }
            comsem.setSelectedItem("select");
            comdept.setSelectedItem("select");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(addstudent.class.getName()).log(Level.SEVERE, null, ex); 
        }
    }
        // TODO add your handling code here:

        // TODO add your handling code here:
    }//GEN-LAST:event_btnsearchActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtrollnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrollnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrollnoActionPerformed

    private void tblattendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblattendanceMouseClicked
     DefaultTableModel model=(DefaultTableModel)tblattendance.getModel();
 int selectedIndex = tblattendance.getSelectedRow();
 
 txtname.setText(model.getValueAt(selectedIndex, 0).toString());
 txtrollno.setText(model.getValueAt(selectedIndex, 1).toString()); 
 comsem1.setSelectedItem(model.getValueAt(selectedIndex, 2).toString());
 comdept1.setSelectedItem(model.getValueAt(selectedIndex, 3).toString());   // TODO add your handling code here:
    }//GEN-LAST:event_tblattendanceMouseClicked

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
    if(comsub.getSelectedItem().equals("select")){
 JOptionPane.showMessageDialog(this,"please select subject");
 comsub.setSelectedItem("select");
 comsub.grabFocus();
 }
 else if(txtname.getText().trim().length()==0){
 JOptionPane.showMessageDialog(this,"please select a row from the table");
 txtname.setText("");
 txtname.grabFocus();
 }
 else if(comstatus.getSelectedItem().equals("select")){
 JOptionPane.showMessageDialog(this,"please select status");
 comstatus.setSelectedItem("select");
 comstatus.grabFocus();
 }
 else{
 try{
 SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
  sdf.format(txtdate.getDate());}
 catch(Exception e){
 JOptionPane.showMessageDialog(null,"please set date");
 }
 try{
 String name=txtname.getText();
 String rollno=txtrollno.getText();
 String subject=(String) comsub.getSelectedItem();
 String semester=(String) comsem1.getSelectedItem();
 String department=(String) comdept1.getSelectedItem();
 String date =((JTextField)txtdate.getDateEditor().getUiComponent()).getText();
 String status=(String) comstatus.getSelectedItem();

 
 Class.forName("com.mysql.jdbc.Driver");
 Connection 
con=DriverManager.getConnection("jdbc:mysql://localhost/attendance_ms","root","");
 PreparedStatement ps=con.prepareStatement("insert into attendance(name,rollno,subject,semester,department,date,status)value(?,?,?,?,?,?,?)");
 
 ps.setString(1,name);
 ps.setString(2,rollno);
 ps.setString(3,subject);
 ps.setString(4,semester);
 ps.setString(5,department);
 ps.setString(6,date);
 ps.setString(7,status);
 
 ps.executeUpdate();
 JOptionPane.showMessageDialog(null,"your data is saved successfully");
 
 txtname.setText("");
 txtrollno.setText("");
 
 comsem1.setSelectedItem("select");
 comdept1.setSelectedItem("select");
 
 comstatus.setSelectedItem("select");
 
 } catch (ClassNotFoundException | SQLException ex) {
 Logger.getLogger(attendance.class.getName()).log(Level.SEVERE, null, ex);
 }
 
 }
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void comdeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comdeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comdeptActionPerformed

    private void ssubjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ssubjectMouseClicked
        // TODO add your handling code here:
        if(comdept.getSelectedItem().equals("select") && comsem.getSelectedItem().equals("select")){
                JOptionPane.showMessageDialog(this,"please select semester and department");
            } else if(comsem.getSelectedItem().equals("select")){
                JOptionPane.showMessageDialog(this,"please select semester");
            } else if(comdept.getSelectedItem().equals("select")){
                JOptionPane.showMessageDialog(this,"please select department");
            } else if(comdept.getSelectedItem().equals("BCA") && comsem.getSelectedItem().equals("VI")){
                comsub.removeAllItems();
                comsub.addItem("select");
                comsub.addItem("DAA");
                comsub.addItem("DM"); 
                comsub.addItem("MC");
            } else if(comdept.getSelectedItem().equals("BCA") && comsem.getSelectedItem().equals("V")){
                comsub.removeAllItems();
                comsub.addItem("select");
                comsub.addItem("A");
                comsub.addItem("B");
                comsub.addItem("C");
            } else if(comdept.getSelectedItem().equals("BCA") && comsem.getSelectedItem().equals("IV")){
                comsub.removeAllItems();
                comsub.addItem("select");
                comsub.addItem("NETWORKS");
                comsub.addItem("MATH");
                comsub.addItem("MCJ");
                comsub.addItem("DBMS");
                comsub.addItem("MATLAB");
                comsub.addItem("SE");
            } else if(comdept.getSelectedItem().equals("BCA") && comsem.getSelectedItem().equals("III")){
                comsub.removeAllItems();
                comsub.addItem("select");
                comsub.addItem("D");
                comsub.addItem("E");
                comsub.addItem("F");
            } else if(comdept.getSelectedItem().equals("BCA") && comsem.getSelectedItem().equals("II")){
                comsub.removeAllItems();
                comsub.addItem("select");
                comsub.addItem("JAVA");
                comsub.addItem("PHYSICS");
                comsub.addItem("C.SYS.ARCH");
            } else if(comdept.getSelectedItem().equals("BCA") && comsem.getSelectedItem().equals("I")){
                comsub.removeAllItems();
                comsub.addItem("select");
                comsub.addItem("G");
                comsub.addItem("H");
                comsub.addItem("I");
            } else if(comdept.getSelectedItem().equals("CS") && comsem.getSelectedItem().equals("VI")){
                comsub.removeAllItems();
                comsub.addItem("select");
                comsub.addItem("AI");
                comsub.addItem("DM");
                comsub.addItem("GRAPHICS");
            } else if(comdept.getSelectedItem().equals("CS") && comsem.getSelectedItem().equals("V")){
                comsub.removeAllItems();
                comsub.addItem("select");
                comsub.addItem("J");
                comsub.addItem("K");
                comsub.addItem("L");
            } else if(comdept.getSelectedItem().equals("CS") && comsem.getSelectedItem().equals("IV")){
                comsub.removeAllItems();
                comsub.addItem("select");
                comsub.addItem("DAA");
                comsub.addItem("MATH");
                comsub.addItem("DBMS");
                comsub.addItem("MATLAB");
                comsub.addItem("SE");
            } else if(comdept.getSelectedItem().equals("CS") && comsem.getSelectedItem().equals("III")){
                comsub.removeAllItems();
                comsub.addItem("select");
                comsub.addItem("M");
                comsub.addItem("N");
                comsub.addItem("O");
            } else if(comdept.getSelectedItem().equals("CS") && comsem.getSelectedItem().equals("II")){
                comsub.removeAllItems();
                comsub.addItem("select");
                comsub.addItem("JAVA");
                comsub.addItem("PHYSICS");
                comsub.addItem("DS");
            } else if(comdept.getSelectedItem().equals("CS") && comsem.getSelectedItem().equals("I")){
                comsub.removeAllItems();
                comsub.addItem("select");
                comsub.addItem("P");
                comsub.addItem("Q");
                comsub.addItem("R");
            }
    }//GEN-LAST:event_ssubjectMouseClicked

    private void ssubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssubjectActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JComboBox<String> comdept;
    private javax.swing.JComboBox<String> comdept1;
    private javax.swing.JComboBox<String> comsem;
    private javax.swing.JComboBox<String> comsem1;
    private javax.swing.JComboBox<String> comstatus;
    private javax.swing.JComboBox<String> comsub;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton ssubject;
    private javax.swing.JTable tblattendance;
    private com.toedter.calendar.JDateChooser txtdate;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtrollno;
    // End of variables declaration//GEN-END:variables
}
