 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.user;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author divya
 */
public class frmlogin extends javax.swing.JFrame {

    /**
     * Creates new form frmlogin
     */
    public frmlogin() {
        initComponents();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnlogin = new javax.swing.JButton();
        btnregister = new javax.swing.JButton();
        txtuser = new javax.swing.JTextField();
        txtpass = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnpass = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnclose = new javax.swing.JLabel();
        logincover = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnlogin.setBackground(new java.awt.Color(255, 102, 0));
        btnlogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(255, 255, 255));
        btnlogin.setText("Login");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));

        btnregister.setBackground(new java.awt.Color(255, 102, 0));
        btnregister.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnregister.setForeground(new java.awt.Color(255, 255, 255));
        btnregister.setText("register");
        btnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, -1, 30));

        txtuser.setBackground(new java.awt.Color(204, 204, 204));
        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });
        getContentPane().add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 264, 26));

        txtpass.setBackground(new java.awt.Color(204, 204, 204));
        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });
        getContentPane().add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 264, 26));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 80, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("New User?");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, -1, -1));

        btnpass.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnpass.setForeground(new java.awt.Color(255, 51, 0));
        btnpass.setText("forgot password?");
        btnpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpassMouseClicked(evt);
            }
        });
        getContentPane().add(btnpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, 16));

        jLabel5.setFont(new java.awt.Font("NSimSun", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Login");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        btnclose.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\com\\user\\icons\\close.png"));
        btnclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncloseMouseClicked(evt);
            }
        });
        getContentPane().add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 20, 30));

        logincover.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        logincover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logincover.setIcon(new javax.swing.ImageIcon("D:\\greenboard2.png")); // NOI18N
        logincover.setIconTextGap(0);
        logincover.setMaximumSize(new java.awt.Dimension(670, 360));
        logincover.setMinimumSize(new java.awt.Dimension(670, 360));
        logincover.setPreferredSize(new java.awt.Dimension(670, 360));
        getContentPane().add(logincover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
       if(txtuser.getText().trim().isEmpty()){
 JOptionPane.showMessageDialog(this,"please enter username");
 txtuser.setText("");
 txtuser.grabFocus(); }
 else if(txtpass.getText().trim().isEmpty()){
 JOptionPane.showMessageDialog(this,"please enter password");
 txtpass.setText("");
 txtpass.grabFocus();
 }
 else{
     String uname;
 uname = txtuser.getText();
 String pass;
 pass = txtpass.getText();
      try {
 Class.forName("com.mysql.jdbc.Driver");
 Connection con;
 con = DriverManager.getConnection("jdbc:mysql://localhost/attendance_ms","root","");
 PreparedStatement ps=con.prepareStatement("select * from users where username=? and password=?");
 ps.setString(1, uname);
 ps.setString(2, pass);
 ResultSet rs = ps.executeQuery();
 if(rs.next()){
 main m = new main();
 this.dispose();;
 m.setVisible(true);; 
 }
 else{
 JOptionPane.showMessageDialog(this, "invalid username or password");
 txtuser.setText("");
 txtpass.setText("");
 txtuser.requestFocus();
 }


 }         catch (ClassNotFoundException | SQLException ex) {    
               Logger.getLogger(frmlogin.class.getName()).log(Level.SEVERE, null, ex);
           }
           // TODO add your handling code here:
    
 // TODO add your handling code here:
    }//GEN-LAST:event_btnloginActionPerformed
    }
    private void btnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregisterActionPerformed
         setVisible(false);
        register r=new register();
       r.setVisible(true);
    }//GEN-LAST:event_btnregisterActionPerformed

    private void btnpassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpassMouseClicked
        setVisible(false);
        forgotpassword f=new forgotpassword();
f.setVisible(true);
    }//GEN-LAST:event_btnpassMouseClicked

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassActionPerformed

    private void btncloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseClicked
    System.exit(0);       
    }//GEN-LAST:event_btncloseMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new frmlogin().setVisible(true);
            }            
        });
    }
         
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnclose;
    private javax.swing.JButton btnlogin;
    private javax.swing.JLabel btnpass;
    private javax.swing.JButton btnregister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel logincover;
    private javax.swing.JTextField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
