 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.user;

import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

import org.apache.poi.ss.formula.functions.T;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author divya
 */
public class leave extends javax.swing.JInternalFrame {

    /**
     * Creates new form leave
     * @throws java.sql.SQLException
     */
    public leave() throws SQLException {
        initComponents();
         tableupdate();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
    ui.setNorthPane(null);
    }
    Connection con;
 PreparedStatement ps;
 ResultSet rs;
public void tableupdate() throws SQLException{
 int c;
 try {
 Class.forName("com.mysql.jdbc.Driver");
 con=DriverManager.getConnection("jdbc:mysql://localhost/attendance_ms","root","");
 ps=con.prepareStatement("select * from leave_record");
 
rs=ps.executeQuery();
 ResultSetMetaData rsd=rs.getMetaData();
c=rsd.getColumnCount();
 DefaultTableModel dft=(DefaultTableModel)tblleave.getModel();
 dft.setRowCount(0); 
 while (rs.next()){
 Vector<String> v2=new Vector<String>();
 Vector<Date> d=new Vector<Date>();
 for(int i=1;i<=c;i++){
 v2.add(rs.getString("name"));
 v2.add(rs.getString("rollno"));
 v2.add(rs.getString("department"));
 v2.add(rs.getString("semester"));
 d.add(rs.getDate("date_from"));
 d.add(rs.getDate("date_to"));
 v2.add(rs.getString("reason"));
 }
 dft.addRow(v2);
 }
 } catch (ClassNotFoundException | SQLException ex) {
 Logger.getLogger(addstudent.class.getName()).log(Level.SEVERE, null, ex);
 } 
 }
    public void openFile(String file) {
        try{
            File path = new File(file);
            Desktop.getDesktop().open(path);
        }catch(IOException ioe) {
            System.out.println(ioe);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        btnsubmit = new javax.swing.JButton();
        txtrollno = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtreason = new javax.swing.JTextArea();
        jLabel31 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtdate = new com.toedter.calendar.JDateChooser();
        txtdate1 = new com.toedter.calendar.JDateChooser();
        comdept = new javax.swing.JComboBox<>();
        comsem = new javax.swing.JComboBox<>();
        btnexport = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblleave = new javax.swing.JTable();

        setBorder(null);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("Roll No:");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setText("Department:");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setText("Semester:");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setText("To:");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setText("From:");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel30.setText("Reason:");

        btnsubmit.setBackground(new java.awt.Color(255, 102, 0));
        btnsubmit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnsubmit.setText("Submit");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });

        txtrollno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtreason.setColumns(20);
        txtreason.setRows(5);
        jScrollPane7.setViewportView(txtreason);

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel31.setText("Name:");

        txtname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtdate.setDateFormatString("yyyy-MM-dd");

        txtdate1.setDateFormatString("yyyy-MM-dd");

        comdept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "BCA", "CS" }));

        comsem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "I", "II", "III", "IV", "V", "VI" }));

        btnexport.setBackground(new java.awt.Color(255, 102, 0));
        btnexport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnexport.setForeground(new java.awt.Color(255, 255, 255));
        btnexport.setText("Export");
        btnexport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexportActionPerformed(evt);
            }
        });

        tblleave.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "name", "roll no", "department", "semester", "date_from", "date_to", "reason"
            }
        ) {
            Class<T>[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class<T> getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblleave.setName(""); // NOI18N
        tblleave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblleaveMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tblleave);

        jScrollPane1.setViewportView(jScrollPane8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel25)
                    .addComponent(jLabel31)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtrollno, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addComponent(txtname)
                    .addComponent(comdept, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comsem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(18, 18, 18)
                                .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel28)
                                .addGap(18, 18, 18)
                                .addComponent(txtdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btnsubmit)
                        .addGap(83, 83, 83)
                        .addComponent(btnexport)))
                .addGap(0, 61, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel28)
                        .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel31)
                        .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel29))
                    .addComponent(txtdate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(txtrollno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(comdept, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(comsem, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsubmit)
                            .addComponent(btnexport))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane1.getAccessibleContext().setAccessibleParent(tblleave);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblleaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblleaveMouseClicked
      
    }//GEN-LAST:event_tblleaveMouseClicked

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        if(txtname.getText().trim().length()==0){
 JOptionPane.showMessageDialog(this,"please enter your name");
 txtname.setText("");
 txtname.grabFocus();
 } 
   else if(txtrollno.getText().trim().length()==0){
 JOptionPane.showMessageDialog(this,"please enter your roll no");
 txtrollno.setText("");
 txtrollno.grabFocus();
 } 
    else if(comdept.getSelectedItem().equals("select")){
 JOptionPane.showMessageDialog(this,"please select your department");
 comdept.setSelectedItem("select");
 comdept.grabFocus();
 }
     else if(comsem.getSelectedItem().equals("select")){
 JOptionPane.showMessageDialog(this,"please select your semester");
 comsem.setSelectedItem("select");
 comsem.grabFocus();
 }
     else if(txtreason.getText().trim().length()==0){
 JOptionPane.showMessageDialog(this,"please enter reason");
 txtreason.setText("");
 txtreason.grabFocus();
 } 
     else {
 try{
 SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
 sdf.format(txtdate.getDate());}
 catch(Exception e){
 JOptionPane.showMessageDialog(null,"please set date");
 }

 try{
 String name=txtname.getText();
 String rollno=txtrollno.getText();
 String semester=(String) comdept.getSelectedItem();
 String department=(String) comsem.getSelectedItem();
 String date_from =((JTextField)txtdate.getDateEditor().getUiComponent()).getText();
 String date_to =((JTextField)txtdate1.getDateEditor().getUiComponent()).getText();
 String reason=txtreason.getText();

 
 Class.forName("com.mysql.jdbc.Driver");
 Connection 
 con=DriverManager.getConnection("jdbc:mysql://localhost/attendance_ms","root","");
 PreparedStatement ps=con.prepareStatement("insert into leave_record(name,rollno,department,semester,date_from,date_to,reason)value(?,?,?,?,?,?,?)");
 
 ps.setString(1,name);
 ps.setString(2,rollno);
 ps.setString(3,department);
 ps.setString(4,semester);
 ps.setString(5,date_from);
 ps.setString(6,date_to);
 ps.setString(7,reason);
 
 ps.executeUpdate();
 JOptionPane.showMessageDialog(null,"your data is saved successfully");
 
 txtname.setText("");
 txtrollno.setText("");
 comdept.setSelectedItem("select");
 comsem.setSelectedItem("select");
 txtdate.setDateFormatString("");
 txtdate1.setDateFormatString("");
 txtreason.setText("");
 
 tableupdate();

 } catch (ClassNotFoundException | SQLException ex) {
 Logger.getLogger(attendance.class.getName()).log(Level.SEVERE, null, ex);
 }
 
 }
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void btnexportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexportActionPerformed
        // TODO add your handling code here:
        
        try{
            JFileChooser jFileChooser = new JFileChooser();
            jFileChooser.showSaveDialog(this);
            File saveFile = jFileChooser.getSelectedFile();
            
            if(saveFile != null) {
                saveFile = new File(saveFile.toString()+".xlsx");
                FileOutputStream out;
                try (Workbook wb = new XSSFWorkbook()) {
                    Sheet sheet = wb.createSheet("customer");
                    Row rowCol = sheet.createRow(0);
                    for (int i=0; i<tblleave.getColumnCount(); i++) {
                        Cell cell = rowCol.createCell(i);
                        cell.setCellValue(tblleave.getColumnName(i));
                    }   for (int j=0; j<tblleave.getRowCount(); j++) {
                        Row row = sheet.createRow(j+1);
                        for (int k=0; k<tblleave.getColumnCount(); k++) {
                            Cell cell = row.createCell(k);
                            if (tblleave.getValueAt(j, k) != null) {
                                cell.setCellValue(tblleave.getValueAt(j, k).toString());
                            }
                        }
                    }   out = new FileOutputStream(new File(saveFile.toString()));
                    wb.write(out);
                }
                out.close();
                openFile(saveFile.toString());   
            }else{
                JOptionPane.showMessageDialog(null, "Error generating file!");
            }
        }catch(FileNotFoundException e) {
            System.out.println(e);
        }catch(IOException io) {
            System.out.println(io);
        }
        
              
    }//GEN-LAST:event_btnexportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexport;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JComboBox<String> comdept;
    private javax.swing.JComboBox<String> comsem;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable tblleave;
    private com.toedter.calendar.JDateChooser txtdate;
    private com.toedter.calendar.JDateChooser txtdate1;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextArea txtreason;
    private javax.swing.JTextField txtrollno;
    // End of variables declaration//GEN-END:variables
}
