/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.user;

import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

import org.apache.poi.ss.formula.functions.T;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author divya
 */
public class studentreport extends javax.swing.JInternalFrame {

    /**
     * Creates new form report
     */
    public studentreport() {
        initComponents(); 
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
    ui.setNorthPane(null);
    }
   
    public void openFile(String file) {
        try {
            File path = new File(file);
            Desktop.getDesktop().open(path);
        } catch (IOException ioe) {
            System.out.println(ioe);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

      
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comdept = new javax.swing.JComboBox<>();
        comsem = new javax.swing.JComboBox<>();
        comsub = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        btnexport = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        fromDate = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblreport = new javax.swing.JTable();
        ssubject = new javax.swing.JButton();
        ssubject1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtrollno = new javax.swing.JTextField();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(852, 580));

        jLabel1.setText("department :");

        jLabel2.setText("semester :");

        jLabel3.setText("subject :");

        comdept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "BCA", "CS", " " }));

        comsem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "I", "II", "III", "IV", "V", "VI" }));

        comsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comsubActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 102, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("view  report");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnexport.setBackground(new java.awt.Color(255, 102, 0));
        btnexport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnexport.setForeground(new java.awt.Color(255, 255, 255));
        btnexport.setText("Export Report");
        btnexport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexportActionPerformed(evt);
            }
        });

        jLabel8.setText("date :");

        fromDate.setDateFormatString("yyyy-MM-dd");

        tblreport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Roll No", "Date", "status"
            }
        ) {
            Class<T>[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class<T> getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblreport);

        jScrollPane2.setViewportView(jScrollPane1);

        ssubject.setText("search subject");

        ssubject1.setText("search subject");
        ssubject1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ssubject1MouseClicked(evt);
            }
        });
        ssubject1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssubject1ActionPerformed(evt);
            }
        });

        jLabel10.setText("roll no : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comsub, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ssubject1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(comdept, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comsem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(txtrollno, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(36, 36, 36)
                                .addComponent(fromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(106, 106, 106))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnexport)
                .addGap(367, 367, 367))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ssubject)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comdept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtrollno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ssubject1))
                            .addComponent(fromDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comsub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(comsem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnexport, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ssubject)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(comdept.getSelectedItem().equals("select")){
            JOptionPane.showMessageDialog(this,"please select your department");
            comdept.setSelectedItem("select");
            comdept.grabFocus();
        } else if(comsem.getSelectedItem().equals("select")) {
            JOptionPane.showMessageDialog(this,"please select your semester");
            comsem.setSelectedItem("select");
            comsem.grabFocus();
        } else if(comsub.getSelectedItem().equals("select")) {
            JOptionPane.showMessageDialog(this,"please select your subject");
            comsub.setSelectedItem("select");
            comsub.grabFocus();
        } else{
            try{
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                sdf.format(fromDate.getDate());}
                catch(Exception e){
                JOptionPane.showMessageDialog(null,"please set from date");
            }

            try{
                String semester=(String) comsem.getSelectedItem();
                String department=(String) comdept.getSelectedItem();
                String subject=(String) comsub.getSelectedItem();
                String date =((JTextField)fromDate.getDateEditor().getUiComponent()).getText();
                String rollno=(String) txtrollno.getText();
                Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost/attendance_ms","root","");
                PreparedStatement ps=con.prepareStatement("select * from attendance where semester='"+semester+"' and department='"+department+"' and subject='"+subject+"' and date='"+date+"' and rollno='"+rollno+"'");
                ResultSet rs=ps.executeQuery();
                
                ResultSetMetaData rsd=rs.getMetaData();
                int c=rsd.getColumnCount(); 
                DefaultTableModel dft=(DefaultTableModel)tblreport.getModel();
                dft.setRowCount(0);
                
                while (rs.next()){
                    Vector<String> v2=new Vector<String>();
                    for(int i=1;i<=c;i++){
                        v2.add(rs.getString("name"));
                        v2.add(rs.getString("rollno"));
                        v2.add(rs.getString("date"));
                        v2.add(rs.getString("status"));
                    }
                    dft.addRow(v2);
                }
                comsem.setSelectedItem("select");
                comdept.setSelectedItem("select");
                comsub.setSelectedItem("select");
                ((JTextField)fromDate.getDateEditor().getUiComponent()).setText("");
                txtrollno.setText("");
            }catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(addstudent.class.getName()).log(Level.SEVERE, null, ex); 
            }
    }//GEN-LAST:event_jButton2ActionPerformed
    }
    private void btnexportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexportActionPerformed
        // TODO add your handling code here:

        try {
            JFileChooser jFileChooser = new JFileChooser();
            jFileChooser.showSaveDialog(this);
            File saveFile = jFileChooser.getSelectedFile();

            if (saveFile != null) {
                saveFile = new File(saveFile.toString() + ".xlsx");
                FileOutputStream out;
                try ( Workbook wb = new XSSFWorkbook()) {
                    Sheet sheet = wb.createSheet("customer");
                    Row rowCol = sheet.createRow(0);
                    for (int i = 0; i < tblreport.getColumnCount(); i++) {
                        Cell cell = rowCol.createCell(i);
                        cell.setCellValue(tblreport.getColumnName(i));
                    }
                    for (int j = 0; j < tblreport.getRowCount(); j++) {
                        Row row = sheet.createRow(j + 1);
                        for (int k = 0; k < tblreport.getColumnCount(); k++) {
                            Cell cell = row.createCell(k);
                            if (tblreport.getValueAt(j, k) != null) {
                                cell.setCellValue(tblreport.getValueAt(j, k).toString());
                            }
                        }
                    }
                    out = new FileOutputStream(new File(saveFile.toString()));
                    wb.write(out);
                }
                out.close();
                openFile(saveFile.toString());
            } else {
                JOptionPane.showMessageDialog(null, "Error generating file!");
            }
        } catch (FileNotFoundException e) {
            System.out.println(e);
        } catch (IOException io) {
            System.out.println(io);
        }
    }//GEN-LAST:event_btnexportActionPerformed

    private void comsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comsubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comsubActionPerformed

    private void ssubject1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssubject1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssubject1ActionPerformed

    private void ssubject1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ssubject1MouseClicked
        // TODO add your handling code here:
        if(comdept.getSelectedItem().equals("select") && comsem.getSelectedItem().equals("select")){
                JOptionPane.showMessageDialog(this,"please select semester and department");
            } else if(comsem.getSelectedItem().equals("select")){
                JOptionPane.showMessageDialog(this,"please select semester");
            } else if(comdept.getSelectedItem().equals("select")){
                JOptionPane.showMessageDialog(this,"please select department");
            } else if(comdept.getSelectedItem().equals("BCA") && comsem.getSelectedItem().equals("VI")){
                comsub.removeAllItems();
                comsub.addItem("select");
                comsub.addItem("DAA");
                comsub.addItem("DM"); 
                comsub.addItem("MC");
            } else if(comdept.getSelectedItem().equals("BCA") && comsem.getSelectedItem().equals("V")){
                comsub.removeAllItems();
                comsub.addItem("select");
                comsub.addItem("A");
                comsub.addItem("B");
                comsub.addItem("C");
            } else if(comdept.getSelectedItem().equals("BCA") && comsem.getSelectedItem().equals("IV")){
                comsub.removeAllItems();
                comsub.addItem("select");
                comsub.addItem("NETWORKS");
                comsub.addItem("MATH");
                comsub.addItem("MCJ");
                comsub.addItem("DBMS");
                comsub.addItem("MATLAB");
                comsub.addItem("SE");
            } else if(comdept.getSelectedItem().equals("BCA") && comsem.getSelectedItem().equals("III")){
                comsub.removeAllItems();
                comsub.addItem("select");
                comsub.addItem("D");
                comsub.addItem("E");
                comsub.addItem("F");
            } else if(comdept.getSelectedItem().equals("BCA") && comsem.getSelectedItem().equals("II")){
                comsub.removeAllItems();
                comsub.addItem("select");
                comsub.addItem("JAVA");
                comsub.addItem("PHYSICS");
                comsub.addItem("C.SYS.ARCH");
            } else if(comdept.getSelectedItem().equals("BCA") && comsem.getSelectedItem().equals("I")){
                comsub.removeAllItems();
                comsub.addItem("select");
                comsub.addItem("G");
                comsub.addItem("H");
                comsub.addItem("I");
            } else if(comdept.getSelectedItem().equals("CS") && comsem.getSelectedItem().equals("VI")){
                comsub.removeAllItems();
                comsub.addItem("select");
                comsub.addItem("AI");
                comsub.addItem("DM");
                comsub.addItem("GRAPHICS");
            } else if(comdept.getSelectedItem().equals("CS") && comsem.getSelectedItem().equals("V")){
                comsub.removeAllItems();
                comsub.addItem("select");
                comsub.addItem("J");
                comsub.addItem("K");
                comsub.addItem("L");
            } else if(comdept.getSelectedItem().equals("CS") && comsem.getSelectedItem().equals("IV")){
                comsub.removeAllItems();
                comsub.addItem("select");
                comsub.addItem("DAA");
                comsub.addItem("MATH");
                comsub.addItem("DBMS");
                comsub.addItem("MATLAB");
                comsub.addItem("SE");
            } else if(comdept.getSelectedItem().equals("CS") && comsem.getSelectedItem().equals("III")){
                comsub.removeAllItems();
                comsub.addItem("select");
                comsub.addItem("M");
                comsub.addItem("N");
                comsub.addItem("O");
            } else if(comdept.getSelectedItem().equals("CS") && comsem.getSelectedItem().equals("II")){
                comsub.removeAllItems();
                comsub.addItem("select");
                comsub.addItem("JAVA");
                comsub.addItem("PHYSICS");
                comsub.addItem("DS");
            } else if(comdept.getSelectedItem().equals("CS") && comsem.getSelectedItem().equals("I")){
                comsub.removeAllItems();
                comsub.addItem("select");
                comsub.addItem("P");
                comsub.addItem("Q");
                comsub.addItem("R");
            }
    }//GEN-LAST:event_ssubject1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexport;
  
    private javax.swing.JComboBox<String> comdept;
    private javax.swing.JComboBox<String> comsem;
    private javax.swing.JComboBox<String> comsub;
    private com.toedter.calendar.JDateChooser fromDate;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton ssubject;
    private javax.swing.JButton ssubject1;
    private javax.swing.JTable tblreport;
    private javax.swing.JTextField txtrollno;
    // End of variables declaration//GEN-END:variables
}
